[package]
name = "mdbook-althtml-example"
version = "0.1.0"
authors = ["rnitta <attinyes@gmail.com>"]
edition = "2018"

[dependencies]
mdbook = "0.2.3"
mdbook-althtml = { path = "../", version = "0.0.1"}
